package edu.hust.k54.hibernate;

// Generated Nov 2, 2012 10:18:44 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Dantoc generated by hbm2java
 */
public class Dantoc implements java.io.Serializable {

	private Integer iddantoc;
	private String ten;
	private Set soyeulyliches = new HashSet(0);

	public Dantoc() {
	}

	public Dantoc(String ten, Set soyeulyliches) {
		this.ten = ten;
		this.soyeulyliches = soyeulyliches;
	}

	public Integer getIddantoc() {
		return this.iddantoc;
	}

	public void setIddantoc(Integer iddantoc) {
		this.iddantoc = iddantoc;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public Set getSoyeulyliches() {
		return this.soyeulyliches;
	}

	public void setSoyeulyliches(Set soyeulyliches) {
		this.soyeulyliches = soyeulyliches;
	}

}
