package edu.hust.k54.persistence;

// Generated Nov 2, 2012 10:18:44 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Chucvu generated by hbm2java
 */
public class Chucvu implements java.io.Serializable {

	private Integer idchucvu;
	private String ten;
	private Set soyeulyliches = new HashSet(0);

	public Chucvu() {
	}

	public Chucvu(String ten, Set soyeulyliches) {
		this.ten = ten;
		this.soyeulyliches = soyeulyliches;
	}

	public Integer getIdchucvu() {
		return this.idchucvu;
	}

	public void setIdchucvu(Integer idchucvu) {
		this.idchucvu = idchucvu;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public Set getSoyeulyliches() {
		return this.soyeulyliches;
	}

	public void setSoyeulyliches(Set soyeulyliches) {
		this.soyeulyliches = soyeulyliches;
	}

}
