package edu.hust.k54.persistence;

// Generated Nov 2, 2012 10:18:44 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Phanquyen generated by hbm2java
 */
public class Phanquyen implements java.io.Serializable {

	private Integer idphanquyen;
	private String ten;
	private Set soyeulyliches = new HashSet(0);

	public Phanquyen() {
	}

	public Phanquyen(String ten, Set soyeulyliches) {
		this.ten = ten;
		this.soyeulyliches = soyeulyliches;
	}

	public Integer getIdphanquyen() {
		return this.idphanquyen;
	}

	public void setIdphanquyen(Integer idphanquyen) {
		this.idphanquyen = idphanquyen;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public Set getSoyeulyliches() {
		return this.soyeulyliches;
	}

	public void setSoyeulyliches(Set soyeulyliches) {
		this.soyeulyliches = soyeulyliches;
	}

}
