package edu.hust.k54.persistence;

// Generated Nov 5, 2012 10:28:07 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Taikhoandangnhap generated by hbm2java
 */
public class Taikhoandangnhap implements java.io.Serializable {

	private int iduser;
	private Soyeulylich soyeulylich;
	private String username;
	private String pass;
	private String email;
	private boolean laCb;
	private int sohieucongchuc;
	private Set nhatkyhethongs = new HashSet(0);

	public Taikhoandangnhap() {
	}

	public Taikhoandangnhap(int iduser, Soyeulylich soyeulylich,
			String username, String pass, String email, boolean laCb,
			int sohieucongchuc) {
		this.iduser = iduser;
		this.soyeulylich = soyeulylich;
		this.username = username;
		this.pass = pass;
		this.email = email;
		this.laCb = laCb;
		this.sohieucongchuc = sohieucongchuc;
	}

	public Taikhoandangnhap(int iduser, Soyeulylich soyeulylich,
			String username, String pass, String email, boolean laCb,
			int sohieucongchuc, Set nhatkyhethongs) {
		this.iduser = iduser;
		this.soyeulylich = soyeulylich;
		this.username = username;
		this.pass = pass;
		this.email = email;
		this.laCb = laCb;
		this.sohieucongchuc = sohieucongchuc;
		this.nhatkyhethongs = nhatkyhethongs;
	}

	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	public Soyeulylich getSoyeulylich() {
		return this.soyeulylich;
	}

	public void setSoyeulylich(Soyeulylich soyeulylich) {
		this.soyeulylich = soyeulylich;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isLaCb() {
		return this.laCb;
	}

	public void setLaCb(boolean laCb) {
		this.laCb = laCb;
	}

	public int getSohieucongchuc() {
		return this.sohieucongchuc;
	}

	public void setSohieucongchuc(int sohieucongchuc) {
		this.sohieucongchuc = sohieucongchuc;
	}

	public Set getNhatkyhethongs() {
		return this.nhatkyhethongs;
	}

	public void setNhatkyhethongs(Set nhatkyhethongs) {
		this.nhatkyhethongs = nhatkyhethongs;
	}

}
